### ISSUE TITLE
donation v16 . Sending Email Error

### ISSUE THREAD

**Issue by dreyeduardo** [OCA/donation#127]
## Module
donation

## Describe the bug
Error when Sending a Donation Tax Receipt 

## To Reproduce
**Affected versions**: 16

1.Open donation module
2.Select Tax Receipt Menu option
3.Select any record 
4. Send By Email
5. SEND

**Expected behavior**
Send succefully the email 

Error:
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "<decorator-gen-6>", line 2, in __getitem__
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.ui.view', <function View._get_view_id at 0x7f8b13891e50>, 2, True, 'donation_base.tax_receipt_email_template', (None,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/wizard/mail_compose_message.py", line 245, in action_send_mail
    self._action_send_mail(auto_commit=False)
  File "/usr/lib/python3/dist-packages/odoo/addons/sale/wizard/mail_compose_message.py", line 15, in _action_send_mail
    return super(MailComposeMessage, self)._action_send_mail(auto_commit=auto_commit)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/wizard/mail_compose_message.py", line 333, in _action_send_mail
    result_messages += ActiveModel.browse(res_id).message_post(**post_params)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 2041, in message_post
    self._notify_thread(new_message, msg_values, **notif_kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/sms/models/mail_thread.py", line 240, in _notify_thread
    recipients_data = super(MailThread, self)._notify_thread(message, msg_vals=msg_vals, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 2419, in _notify_thread
    self._notify_thread_by_email(message, recipients_data, msg_vals=msg_vals, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 2543, in _notify_thread_by_email
    mail_body = self.env['ir.qweb']._render(template_xmlid, render_values, minimal_qcontext=True, raise_if_not_found=False, lang=template_values['lang'])
  File "/usr/lib/python3/dist-packages/odoo/tools/profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 577, in _render
    template_functions, def_name = irQweb._compile(template)
  File "/usr/lib/python3/dist-packages/odoo/tools/profiler.py", line 300, in _tracked_compile
    return method_compile(self, template)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 640, in _compile
    return self._load_values(base_key_cache, generate_functions)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 2443, in _load_values
    return get_value()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 615, in generate_functions
    code, options, def_name = self._generate_code(template)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 665, in _generate_code
    element, document, ref = self._get_template(template)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 792, in _get_template
    doc_or_elem, ref = self._load(ref_alias) or (None, None)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 829, in _load
    view = IrUIView._get(ref)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 2023, in _get
    return self.browse(self._get_view_id(view_ref))
  File "<decorator-gen-216>", line 2, in _get_view_id
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 367, in _get_view_id
    return super(View, self.sudo())._get_view_id(xml_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 2015, in _get_view_id
    assert res_model == self._name, "Call _get_view_id, expected %r, got %r" % (self._name, res_model)
AssertionError: Call _get_view_id, expected 'ir.ui.view', got 'mail.template'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://aussiehelperserp.com.au/web/assets/debug/web.assets_backend.js:10360:19) (/web/static/src/core/network/rpc_service.js:34)
    at XMLHttpRequest.<anonymous> (https://aussiehelperserp.com.au/web/assets/debug/web.assets_backend.js:10413:27) (/web/static/src/core/network/rpc_service.js:87)

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by dreyeduardo** [comment]
Fixed.

I just changed : donation_base module , model/donation_tax_receipt.py

layout_xmlid = "donation_base.tax_receipt_email_template"

for:

compose_form = self.env.ref("mail.email_compose_message_wizard_form")
