### ISSUE TITLE
Error on validate a new donation

### ISSUE THREAD

**Issue by ulisesgamboa** [OCA/donation#50]
Please your help to solve this issue.

Regards

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/addons/mail/models/mail_thread.py", line 241, in create
    thread.message_post(body=_('%s created') % doc_name)
  File "/odoo/odoo-server/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(body=body, subject=subject, message_type=message_type, subtype=subtype, parent_id=parent_id, attachments=attachments, content_subtype=content_subtype, **kwargs)
  File "/odoo/odoo-server/addons/mail/models/mail_thread.py", line 1909, in message_post
    new_message = MailMessage.create(values)
  File "/odoo/odoo-server/addons/mail/models/mail_message.py", line 753, in create
    values['record_name'] = self._get_record_name(values)
  File "/odoo/odoo-server/addons/mail/models/mail_message.py", line 709, in _get_record_name
    return self.env[model].sudo().browse(res_id).name_get()[0][1]
  File "/odoo/custom/addons/donation/donation_recurring/models/donation.py", line 68, in name_get
    name = _('Draft Donation of %s') % donation.partner_id.name
TypeError: not all arguments converted during string formatting

**Comment by ulisesgamboa** [comment]
hi team,

Some one can help to resolve this issue?

Regards

**Comment by geluboros** [comment]
Hi @ulisesgamboa ,

I don't know if you were able to fix the problem, but it seems to be occurring still.

The problem comes from the module's translations. For example, for ES:

msgid "Cancelled Donation of %s"
msgstr "Validar donativos"

As you can see, the original term has %s, while the translated term doesn't. This generates the formatting error, when your user is in that language.

This can be fixed easily by updating the translation terms in your database or in this repository directly via Weblate.

Regards

**Comment by luistorresm** [comment]
Hello @ulisesgamboa

I cannot replicate the error in the Runbot, if you yet have the error, could add the steps to get it?

Regards

**Comment by geluboros** [comment]
Hi @luistorresm,

Try switching the user's language to Spanish and create a donation.

Check my previous comment:
https://github.com/OCA/donation/issues/50#issuecomment-469603155

Regards

**Comment by ulisesgamboa** [comment]
> Hi @ulisesgamboa ,
> I don't know if you were able to fix the problem, but it seems to be occurring still.
> The problem comes from the module's translations. For example, for ES:
> msgid "Cancelled Donation of %s"
> msgstr "Validar donativos"
> As you can see, the original term has %s, while the translated term doesn't. This generates the formatting error, when your user is in that language.
> This can be fixed easily by updating the translation terms in your database or in this repository directly via Weblate.
> Regards

Thanks for your response, it Help us to complete our testings here in Mexico.

Regards
